nationalarchives/tdr-github-actions

.github/workflows/ecs_deploy.yml

Enironment is not an input variable or a word.
Also, I missed off the final curly bracket.

Correct typo

---

.github/workflows/ecs_deploy.yml

Secrets need to be passed explicitly from the calling job.

Add account number secret.

---

.github/workflows/sbt_release.yml

This will run sbt release.
The GPG secrets are for deploying this to maven.

Add sbt release job

---

.github/workflows/sbt_release.yml

- Use GPG key to sign commits.
- Use GitHub cli to create the PR. At the moment it's being created by a bot and this isn't triggering the tests.

Use gpg to sign commits

---

.github/workflows/sbt_release.yml

This will allow us to skip the deploy job for any PR that has this
label.

Add label for version bump PR

---

.github/workflows/scala_steward.yml

Despite being asked and saying this was once per day, it isn't, it's
once per week and it's running at midnight which is a busy time because
everyone sets their cron schedule like this.
I've change this to now run at 08:15 every day.
I used this site to confirm
https://crontab.guru/#15_8_*_*_*

Use correct cron expression.

---

.github/workflows/terraform_apply.yml

- Use working directory for apply
- Use the full path to the script

Use working directory for apply

---

repos.md

We now have a proper multi-project sbt project for the auth server so
Scala Steward should work now.

Add tdr-auth-server.

---

repos.md

We can start getting even more depenency updates now

Add rotate secrets repo to Scala Steward list

---

.github/workflows/lambda_deploy.yml

all_env_vars needs to be a set before you can call difference on it.

Convert filter object to set

---

.github/workflows/sbt_release.yml

This isn't used in the workflow.

Remove unused parameter

---

.github/workflows/ecs_build.yml
.github/workflows/tdr_test.yml

Ran the changes with the tdr-auth-server builds and work.

Upgrade java version

---

.github/workflows/lambda_deploy.yml

Input of 'project' to allow for the hosting of non-TDR lambdas

Reference counter lambda is prefix with 'da' as TDR only hosting it

---

.github/workflows/create-dependencies-pull-requests.yml
repos.md

- Modify the script to be a cron job that runs weekly or manually run. 
- Remove archived tdr-sign-cookies repo
- reference correct branch when creating pr

Create pull request script modifications

---

repos.md

Transfer Service causing issues as not fully configured yet

Remove transfer service repo

---

.github/workflows/ecr_image_env_tag.yml
.github/workflows/ecr_image_tag.yml
.github/workflows/lambda_deploy.yml

Workflow to allow env tagging of an ecr image
Extracted from the ecs_deploy.yml

Version tag ecr

---

.github/workflows/ecs_deploy.yml
.github/workflows/lambda_deploy.yml
.github/workflows/terraform_apply.yml

Requires: https://github.com/nationalarchives/tdr-e2e-tests/pull/848

TDRD-520 Pass repo details to e2e tests

---

.github/workflows/create-dependencies-pull-requests.yml
.github/workflows/tdr_test.yml

After creating a PR from scala-steward-dependencies update it with `main/master` so that Mergify can merge it without any issue

Tdrd 524 update scala steward branch

---

.github/workflows/ecs_build.yml

This allows us to see the scan reports

Provide `wiz_project_id` to the wiz scans

---

.github/workflows/lambda_build.yml

Add missing if statement to wiz authentication step

Optionally authenticate wiz api
