nationalarchives/tdr-github-actions

.github/workflows/ecs_deploy.yml
Without this, it tries to run python in bash which oddly enough doesn't work.
=> Run python in python shell.

.github/actions/get-next-version/action.yml, .github/workflows/lambda_build.yml
This uses an optional parameter to find the built jar so we can do lambda/target/scala-2.13
I've also updated the get-next-version action so it will work with semver tags as well as the v100 ones we use elsewhere.
=> Allow sub project builds and semver tags

.github/workflows/ecs_deploy.yml
The e2e tests job has been updated to take a wait parameter which makes
it sleep for x seconds.
I've added in the parameter here to give the load balancer time to
switch to the new version.
=> Add wait parameter to e2e tests call

.github/actions/run-git-secrets/entrypoint.sh
Git suggest making this change.
Due to a security alert: https://github.blog/2022-04-12-git-security-vulnerability-announced/
See this stackoverflow thread: https://stackoverflow.com/questions/71849415/cannot-add-parent-directory-to-safe-directory-on-git
=> Set workspace as safe

.github/workflows/lambda_build.yml
This currently only allows files called ***.jar. Some function packages
are .zip.
I could change it so the artifact-name has the suffix but that will
break the existing deployments that use this so I'll put this in for now
and maybe update it later.
=> Allow different file types

.github/workflows/terraform_check.yml
Allow other working directories
Terraform is not always run from the root directory. This allows another one to be specified
=> Allow other working directories for terraform check

.github/workflows/terraform_apply.yml
This is the job that runs terraform plan, uploads the plan to Cloudwatch and then requests approval to apply. It's mostly lifted from the job in tdr-terraform-environments.
The reason I'm splitting it out into here is because we have other terraform apply jobs like the AWS accounts deploy so I think this is worth it.
The only slightly annoying part is that you have to pass INTG_ACCOUNT_NUMBER, STAGING_ACCOUNT_NUMBER and PROD_ACCOUNT_NUMBER. The plan step is run outside of the GitHub environment which means we don't have to approve that step but because of that, we need to pass all three accounts because the reusable workflow doesn't know in advance which one it will need.
=> Add terraform apply job

.github/workflows/lambda_deploy.yml
This runs a python script inline:
It runs a regex search looking for the {ENV_VAR} lines in the conf file. Then it gets the env vars from the lambda
It then compares them and fails if any are missing in the lambda.
The python is all sqashed together because I can't have it in a separate file inside a custom action.
=> Add script to check deployed environment variables

.github/workflows/lambda_deploy.yml
The call to get the environment variables doesn't return
AWS_LAMBDA_FUNCTION_NAME as that's a "hidden" environment variable that
lambda provides.
It is sometimes in the application conf files though so it needs to be
filtered from those variables rather than the lambda variables.
=> Put the lambda function name filter in the right place

.github/.scala-steward.conf
We've been ignoring the 2.17.xx versions of the AWS libraries because they release new ones every day. They're up to 2.18.11 now so we can safely ignore all the 2.18 updates for now.
=> Update minor version on AWS libraries

.github/.scala-steward.conf
The AWS libraries are on 2.19.x now so we're getting updates every time as they're release every day. I've also added the jaxb library. This is only used by the new file format as it's needed by the Droid library. This will break if upgraded so we need to stop trying.
=> Update the ignore list

repos.md
tdr-download-files has been archived and there's three new repos for the
backend checks which need updating.
=> Update repos list

.github/.scala-steward.conf
AWS now have version 2.20. This is being deployed but we want to ignore
all the patch versions until 2.21 because they release them every day.
=> Version bump AWS SDK in ignore list.

.github/workflows/terraform_apply.yml
The variable being set on the GITHUB_OUTPUT file was `title-environment` but the outputs which were set to the next stage of the build was `title_environment` so the environment was going in empty so the role name didn't match one that exists in the management account so the assume role failed because the role doesn't exist.
This is Python so we'll stick with snake case as that's what it was before.
=> Fix the inconsistent case.

.github/actions/run-git-secrets/entrypoint.sh
This account belongs to AWS and isn't secret. It's used when we're matching a given AMI.
=> Add AWS AMI account to allowed secrets

.github/workflows/ecs_build.yml, .github/workflows/tdr_test.yml
Not all ECS tasks are compatible with Java version 17
Optional input to set the Java version with default to Java version 11
Allow any tasks requiring higher version of Java to pass in required version and all other tasks to build correctly
=> Use 'java-version' input

.github/workflows/lambda_deploy.yml
Prevent e2e tests running for the ''mgmt' account
=> Some lambdas deploy to 'mgmt' account

.github/workflows/ecs_deploy.yml, .github/workflows/lambda_deploy.yml
At present, by leaving the arguments to the `checkout` action blank we checkout the calling branch (generally `master`/`main`) whilst running the our deploy workflow. This means that we update our release branch after deployment, it is set to the version tag at the current `HEAD`, regardless of whether a rollback is being performed, or if a higher environment is being deployed to a tagged version behind the latest merged change. 
By checking out with the tag of the deployed version, we can ensure that our release branches are accurately tagged moving forward.
---
Deployed `tdr-transfer-frontend` on intg from `master` to a version prior. Verified that the `intg-release` branch remained at the latest commit from `master`. Redeployed from `master` up to the current version. Deployed from a …
=> fix: Checkout deployed tag at outset of workflow so that release branch is updated correctly

.github/workflows/create-dependencies-pull-requests.yml
- To determine whether there have been updates to the scala steward repo, check the length of `diff`ing the branches rather than comparing the SHAs of each branch's tip (if `scala-steward-dependencies` has merged in the default branch, the content will be identical but the hashes different, causing a failure)
- Don't attempt to create a pull request if there is already a pull request open for `scala-steward-dependencies` into the default branch
=> Mitigations against hard failures in scala steward dependencies PR creation script

.github/workflows/ecs_build.yml
Since this is a reusable workflow the calling workflows need to pass the wiz secrets
=> Accept Wiz secret variables

.github/workflows/lambda_build.yml
Turns out the `tdr-signed-cookies` and `tdr-reporting` uses a docker file to build the lambda. This adds wiz-cli to the lambda build pipeline to scan dockerfile and docker image if the `inputs.build-command` contains "docker"
=> Add wiz cli to lambda build
